#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 17 03:04:59 2025

@author: caio
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from catboost import CatBoostRegressor

class ModeloCat:
    def __init__(self, data_treino_path, data_teste_path):
        self.data_treino_path = data_treino_path
        self.data_teste_path = data_teste_path
        self.modelo = CatBoostRegressor(
            iterations=1000,
            learning_rate=0.05,
            depth=6,
            loss_function='RMSE',
            verbose=0,
            random_state=42
            )
        
    def carregar_data(self):
        self.data_treino = pd.read_csv(self.data_treino_path)
        self.data_teste = pd.read_csv(self.data_teste_path)
        self.feature = self.data_treino.drop('Calories', axis=1)
        self.target = self.data_treino['Calories']
        
        
if __name__ == "__main__":
    preditor = ModeloCat(
        data_treino_path = '/home/caio/github/Kaggle S5E5/data/final.csv',
        data_teste_path = '/home/caio/github/Kaggle S5E5/data/csv_para_previsao.csv'
        )
    
    preditor.carregar_data()
