#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 17 04:00:31 2025

@author: caio
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

class EDA:
    def __init__():